apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: piston-runner-external-secret
  namespace: bitbucket
spec:
  refreshInterval: "2h"
  secretStoreRef:
    name: bitbucket-secretstore
    kind: SecretStore
  target:
    name: piston-runner-oauth-credentials
    creationPolicy: Owner
  data:
  - secretKey: OAUTH_CLIENT_ID
    remoteRef:
      key: Bitbucket
      property: PISTON_RUNNER_OAUTH_CLIENT_ID
  - secretKey: OAUTH_CLIENT_SECRET
    remoteRef:
      key: Bitbucket
      property: PISTON_RUNNER_OAUTH_CLIENT_SECRET
