apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitbucket-secretstore
  namespace: bitbucket
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
