apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-external-secret
  namespace: ai-mcp
spec:
  refreshInterval: "2h"
  secretStoreRef:
    name: mcp-secretstore
    kind: SecretStore
  target:
    name: mcp-credentials
    creationPolicy: Owner
  data:
  - secretKey: GRAFANA_SERVICE_ACCOUNT_TOKEN
    remoteRef:
      key: "MCP"
      property: GRAFANA_SERVICE_ACCOUNT_TOKEN
