{
 "title": "ArgoCD Overview",
 "description": "A comprehensive Grafana dashboard for monitoring ArgoCD applications, clusters, and controller metrics. This dashboard provides real-time insights into your GitOps deployment pipeline, application health, sync status, and performance metrics.",
 "tags": [
  "ArgoCD",
  "DEV"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(argocd_app_info{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, job)"
   },
   {
    "name": "kubernetes_cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, dest_server)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$kubernetes_cluster\"}, project)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$kubernetes_cluster\", project=~\"$project\"}, name)"
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknowns"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (health_status)\n",
     "legendFormat": "{{ health_status }}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (sync_status)\n",
     "legendFormat": "{{ sync_status }}"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (job, dest_server, project, name, health_status, sync_status)\n"
    }
   ]
  },
  { "title": "Summary by Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Application Health Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (job, project, health_status)\n",
     "legendFormat": "{{ project }} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (job, project, sync_status)\n",
     "legendFormat": "{{ project }} - {{ sync_status }}"
    }
   ]
  },
  {
   "title": "Application Syncs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n      }[$__rate_interval]\n    )\n  )\n) by (job, project, phase)\n",
     "legendFormat": "{{ project }} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Application Auto Sync Enabled",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n  }\n) by (job, project, autosync_enabled)\n",
     "legendFormat": "{{ project }} - {{ autosync_enabled }}"
    }
   ]
  },
  {
   "title": "Applications (Unhealthy/OutOfSync/AutoSyncDisabled) Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Applications Unhealthy",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n    health_status!~\"Healthy|Progressing\"\n  }\n) by (job, dest_server, project, name, health_status)\n"
    }
   ]
  },
  {
   "title": "Applications Out Of Sync",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n    sync_status!=\"Synced\"\n  }\n) by (job, dest_server, project, name, sync_status) > 0\n"
    }
   ]
  },
  {
   "title": "Applications That Failed to Sync[7d]",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n        phase!=\"Succeeded\"\n      }[7d]\n    )\n  )\n) by (job, dest_server, project, name, phase) > 0\n"
    }
   ]
  },
  {
   "title": "Applications With Auto Sync Disabled",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n    autosync_enabled!=\"true\"\n  }\n) by (job, dest_server, project, name, autosync_enabled) > 0\n"
    }
   ]
  },
  {
   "title": "Application ($application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Application Health Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n    name=~\"$application\",\n  }\n) by (namespace, job, dest_server, project, name, health_status)\n",
       "legendFormat": "{{ project }}/{{ name }} - {{ health_status }}"
      }
     ]
    },
    {
     "title": "Application Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n    name=~\"$application\",\n  }\n) by (namespace, job, dest_server, project, name, sync_status)\n",
       "legendFormat": "{{ project }}/{{ name }} - {{ sync_status }}"
      }
     ]
    },
    {
     "title": "Application Sync Result",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        cluster=\"$cluster\",\nnamespace=~'$namespace',\njob=~'$job',\ndest_server=~'$kubernetes_cluster',\nproject=~'$project',\n\n        name=~\"$application\",\n      }[$__rate_interval]\n    )\n  )\n) by (namespace, job, dest_server, project, name, phase)\n",
       "legendFormat": "{{ project }}/{{ name }} - {{ phase }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Summary - Notification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notification Deliveries -zoho",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  round(\n    increase(\n      argocd_notifications_deliveries_total{\nnamespace=~'$namespace',\njob=\"argo-cd-argocd-notifications-controller-metrics\",\n\n        exported_service=\"zoho\",\n      }[10m]\n    )\n  )\n) by (job, exported_service, succeeded)\n",
       "legendFormat": "{{ exported_service }} - Succeeded: {{ succeeded }}"
      }
     ]
    },
    {
     "title": "Notification Deliveries - drsite",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  round(\n    increase(\n      argocd_notifications_deliveries_total{\nnamespace=~'$namespace',\njob=\"argo-cd-argocd-notifications-controller-metrics\",\n\n        exported_service=\"argocd-drsite\",\n      }[10m]\n    )\n  )\n) by (job, exported_service, succeeded)\n",
       "legendFormat": "{{ exported_service }} - Succeeded: {{ succeeded }}"
      }
     ]
    },
    {
     "title": "Trigger Evaluations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  round(\n    increase(\n      argocd_notifications_trigger_eval_total{\nnamespace=~'$namespace',\njob=\"argo-cd-argocd-notifications-controller-metrics\",\n\n      }[10m]\n    )\n  )\n) by (job, name, triggered)\n",
       "legendFormat": "{{ name }} - Triggered: {{ triggered }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciliation Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_count{namespace=~\"$namespace\",dest_server=\"https://kubernetes.default.svc\"}[10m])) ",
       "legendFormat": "ArgoCD"
      }
     ]
    },
    {
     "title": "Reconciliation Performance",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~\"$namespace\"}[10m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "K8s API Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_k8s_request_total{namespace=~\"$namespace\",server=\"https://10.233.0.1:443\"}[10m])) by (verb, resource_kind)",
       "legendFormat": "{{verb}} {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(workqueue_depth{namespace=~\"$namespace\",name=~\"app_.*\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pending kubectl run",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_kubectl_exec_pending{namespace=~\"$namespace\"}) by (command)",
       "legendFormat": "{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Objects Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_cluster_api_resource_objects{namespace=~\"$namespace\",server=\"https://kubernetes.default.svc\"}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "API Resources Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(argocd_cluster_api_resources{namespace=~\"$namespace\",server=\"https://kubernetes.default.svc\"}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Cluster Events Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_cluster_events_total{namespace=~\"$namespace\",server=\"https://kubernetes.default.svc\"}[15m])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by result",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_redis_request_total{namespace=~\"$namespace\"}[$interval])) by (failed)"
      }
     ]
    }
   ]
  }
 ]
}