apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-updater-external-secret
  namespace: argocd
spec:
  refreshInterval: "2h"
  secretStoreRef:
    name: argocd-secretstore
    kind: SecretStore
  target:
    name: argocd-image-updater-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: Argo
      property: bitbucket.user
  - secretKey: password
    remoteRef:
      key: Argo
      property: bitbucket.token
