apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-external-secret
  namespace: argocd
spec:
  refreshInterval: "2h"
  secretStoreRef:
    name: argocd-secretstore
    kind: SecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
  - secretKey: smtp-username
    remoteRef:
      key: "SMTP1"
      property: username
  - secretKey: smtp-password
    remoteRef:
      key: "SMTP1"
      property: password
