apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-external-secret
  namespace: monitoring
spec:
  refreshInterval: "2h"
  secretStoreRef:
    name: monitoring-secretstore
    kind: SecretStore
  target:
    name: smtp-credentials
    creationPolicy: Owner
  data:
  - secretKey: user
    remoteRef:
      key: "SMTP1"
      property: username
  - secretKey: password
    remoteRef:
      key: "SMTP1"
      property: password
