apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: saha-nodes-dynamic
spec:
  template:
    metadata:
      labels:
        node-group: saha_nodes_karpenter
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-v2
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["t3a.large"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
