apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-external-secret
  namespace: oauth2-proxy
spec:
  refreshInterval: "2h"
  secretStoreRef:
    name: oauth2-proxy-secretstore
    kind: SecretStore
  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner
  data:
  - secretKey: client-id
    remoteRef:
      key: Azure-ad
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: Azure-ad
      property: client-secret
  - secretKey: cookie-secret
    remoteRef:
      key: Azure-ad
      property: cookie-secret
