apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: oauth2-proxy-secretstore
  namespace: oauth2-proxy
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
