apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:Alizandieh/gitops-argocd.git
  sshPrivateKey: |
    <SSH private key here>
  type: git
