apiVersion: v1
kind: Secret
metadata:
  name: helm-charts-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:Alizandieh/helm-chart.git
  sshPrivateKey: |
    <SSH private key here>
  type: git
